#-----------------------------------------------------------------------------#
#                                                                             #
# ARRANQUE/PARADA DEL SISTEMA                                                 #
#                                                                             #
#-----------------------------------------------------------------------------#
- id: hass_startup_automation
  alias: hass_startup_scripts
  trigger:
    platform: homeassistant
    # Event can also be 'shutdown'
    event: start
  action:
    #
    # Llamada al script python para inicializar meta-trackers
    - service: python_script.meta_device_tracker
      data_template:
        entity_id: device_tracker.b8b52a3bf0384e72a268705d9b06e496 #AAC
    - service: python_script.meta_device_tracker
      data_template:
        entity_id: device_tracker.e3c67d6b51bf445ba241a0045bfe0222 #MFC
    - service: python_script.meta_device_tracker
      data_template:
        entity_id: device_tracker.93e3d52336a54d4d898b204abdf3ee94 #PAF
    - service: python_script.meta_device_tracker
      data_template:
        entity_id: device_tracker.bef743fa74f2464ba458612ad3e1c195 #AAF
    #
    # Llamada al contador de personas que actualiza sensor.family_home
    - service: python_script.countpeople

#-----------------------------------------------------------------------------#
#                                                                             #
# FAMILY META TRACKER HOME/AWAY                                               #
#                                                                             #
#-----------------------------------------------------------------------------#

# NMAP ==> prob_given_true: 0.8 - prob_given_false: 0.2
#   - entity_id: device_tracker.aac_iphone_nmap
#   - entity_id: device_tracker.mfc_iphone_nmap
#   - entity_id: 'device_tracker.pi_rashmiphone'
#   - entity_id: 'device_tracker.pi_alokphone'

# IOS APP ==> prob_given_true: 0.99 - prob_given_false: 0.10
#   - device_tracker.aac_ios
#   - device_tracker.mfc_ios
#   - entity_id: 'device_tracker.rashmiappiphone'
#   - entity_id: 'device_tracker.alokiosiphone'

# OWNTRACK ==> prob_given_true: 0.99 - prob_given_false: 0.4
#   - device_tracker.aac_iphone_owntrack
#   - device_tracker.mfc_iphone_owntrack
#   - entity_id: 'device_tracker.rashmisiphone'
#   - entity_id: 'device_tracker.myiphone'

# GEOFENCY ==> prob_given_true: 0.99 - prob_given_false: 0.1
#   - device_tracker.b8b52a3bf0384e72a268705d9b06e496 #AAC
#   - device_tracker.e3c67d6b51bf445ba241a0045bfe0222 #MFC
#   - device_tracker.93e3d52336a54d4d898b204abdf3ee94 #PAF
#   - device_tracker.bef743fa74f2464ba458612ad3e1c195 #AAF
#   - entity_id: 'device_tracker.6b00226793104872afb9248f8a45f957'
#   - entity_id: 'device_tracker.3a196aa7e85e4ab5bee4e3d3af667a09'

- id: update_meta_tracker
  alias: "Update Device Meta Tracker"
  initial_state: 'on'
  trigger:
    # Delayed action for router-based and Owntracks trackers that are not 100% reliable
    - platform: state
      entity_id:
        - device_tracker.aac_iphone_nmap      # NMAP
        - device_tracker.mfc_iphone_nmap      # NMAP
        - device_tracker.paf_iphone_nmap      # NMAP
        - device_tracker.aaf_iphone_nmap      # NMAP
        - device_tracker.aac_iphone_owntrack  # OWNTRACK
        - device_tracker.mfc_iphone_owntrack  # OWNTRACK
      to: 'not_home'
      for: '00:07:00'
    - platform: state
      entity_id:
        - device_tracker.aac_iphone_owntrack  # OWNTRACK
        - device_tracker.mfc_iphone_owntrack  # OWNTRACK
      to: 'home'
    - platform: state
      entity_id:
        - device_tracker.aac_iphone_nmap      # NMAP
        - device_tracker.mfc_iphone_nmap      # NMAP
        - device_tracker.paf_iphone_nmap      # NMAP
        - device_tracker.aaf_iphone_nmap      # NMAP
      to: 'home'
      for: '00:00:30'
    - platform: state
      entity_id:
        - device_tracker.aac_ios                          # IOSAPP
        - device_tracker.mfc_ios                          # IOSAPP
        - device_tracker.b8b52a3bf0384e72a268705d9b06e496 # AAC
        - device_tracker.e3c67d6b51bf445ba241a0045bfe0222 # MFC
        - device_tracker.93e3d52336a54d4d898b204abdf3ee94 # PAF
        - device_tracker.bef743fa74f2464ba458612ad3e1c195 # AAF
  action:
    - service: script.updatetracker
      data_template:
        entityid: '{{trigger.entity_id}}'
        fromstate: '{{trigger.from_state.state}}'
        tostate: '{{trigger.to_state.state}}'

#-----------------------------------------------------------------------------#
#                                                                             #
# TRACKING FAMILY AT HOME: Control Home/Away                                  #
#                                                                             #
#-----------------------------------------------------------------------------#

- id: T01_family_away
  alias: 'T01 Family Away'
  trigger:
    # Ya no hay nadie en casa
    platform: state
    entity_id: binary_sensor.family_any_home
    from: 'on'
    to: 'off'
  action:
    # Script Luces Apagado Total
    - service: script.turn_on
      entity_id: script.luces_off
    # Servicio Alarma Armado Total
    - service: alarm_control_panel.alarm_arm_away
      data:
        entity_id: alarm_control_panel.ha
        code: !secret alarm_control_code
    # Notifica a Familia NADIE en Casa
    - service: script.turn_on
      entity_id: script.notifica_evento
      data:
        variables:
          title: '*FAMILY_HOME: NO*'
          message: >
            >>> EVENTO: Último en Salir {{ states('sensor.family_last_tracking') }}

- id: T02_family_at_home
  alias: 'T02 Family at Home'
  trigger:
    # Hay alguien en casa
    - platform: state
      entity_id: binary_sensor.family_any_home
      from: 'off'
      to: 'on'
  action:
    # Script encendido Luz piloto si es de noche
    - service: script.turn_on
      entity_id: script.luces_on_family_home
    # Servicio Alarma Desarmado
    - service: alarm_control_panel.alarm_disarm
      data:
        entity_id: alarm_control_panel.ha
        code: !secret alarm_control_code
    # Notifica a Familia Alguien en Casa
    - service: script.turn_on
      entity_id: script.notifica_evento
      data:
        variables:
          title: '*FAMILY_HOME: SI*'
          message: >
            >>> EVENTO: Último en Entrar {{ states('sensor.family_last_tracking') }}

#-----------------------------------------------------------------------------#
#                                                                             #
# ALARMA: Armado y Control de la Alarma                                       #
#                                                                             #
#-----------------------------------------------------------------------------#
- id: A1_intrusion_alarma_away
  alias: 'A1 Intrusión con Alarma Armado Away'
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0001e55903
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d00022b393c
      from: 'off'
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: alarm_control_panel.ha
        state: armed_away
      - condition: state
        entity_id: binary_sensor.family_any_home
        state: 'off'
  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.alarm_mode
    - service: xiaomi_aqara.play_ringtone
      data:
        gw_mac: 78:11:DC:B7:88:FA
        ringtone_id: 1
        ringtone_vol: 100
    # Script Notificación Alarma
    - service: script.turn_on
      entity_id: script.notifica_alarma
      data:
        variables:
          title: '*ALARMA*'
          message: >
            >>> URGENTE: ALARMA EN CASA

            >>> ZONA: Entrada

            >>> SIRENA: Sirena sonando

    # Script Envio Fotos Cámaras Telegram
    - service: script.turn_on
      entity_id: script.telegram_alarm_send_photo

- id: A2_intrusion_alarma_home
  alias: 'A2 Intrusión con Alarma Armado Parcial'
  trigger:
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d00022b393c
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: alarm_control_panel.ha
      state: armed_home
  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.alarm_mode
    - service: xiaomi_aqara.play_ringtone
      data:
        gw_mac: 78:11:DC:B7:88:FA
        ringtone_id: 1
        ringtone_vol: 100
    # Script Notificación Alarma
    - service: script.turn_on
      entity_id: script.notifica_alarma
      data:
        variables:
          title: '*ALARMA*'
          message: >
            >>> URGENTE: ALARMA EN CASA

            >>> ZONA: Entrada

            >>> SIRENA: Sirena sonando

    # Script Envio Fotos Cámaras Telegram
    - service: script.turn_on
      entity_id: script.telegram_alarm_send_photo


- id: A3_alarma_boton_panico_on
  alias: 'A3 Alarma Boton Panico On'
  trigger:
    platform: state
    entity_id: input_boolean.alarm_mode
    from: 'off'
    to: 'on'
  action:
    - service: xiaomi_aqara.play_ringtone
      data:
        gw_mac: 78:11:DC:B7:88:FA
        ringtone_id: 1
        ringtone_vol: 100
    - service: script.turn_on
      entity_id: script.notifica_alarma
      data:
        variables:
          title: '*ALARMA*'
          message: >
            >>> URGENTE: BOTON PANICO ACTIVADO


- id: A4_alarma_boton_panico_off
  alias: 'A4 Alarma Boton Panico Off'
  trigger:
    platform: state
    entity_id: input_boolean.alarm_mode
    from: 'on'
    to: 'off'
  action:
    - service: xiaomi_aqara.stop_ringtone
      data:
        gw_mac: 78:11:DC:B7:88:FA
    # Servicio Alarma Desarmado
    - service: alarm_control_panel.alarm_disarm
      data:
        entity_id: alarm_control_panel.ha
        code: !secret alarm_control_code
    - service: script.turn_on
      entity_id: script.notifica_alarma
      data:
        variables:
          title: '*ALARMA*'
          message: >
            >>> URGENTE: BOTON PANICO APAGADO

            >>> PANEL ALARMA: DESARMADO

#
# CERTBOT SSL CERTIFICATE: ALERT TO WARN US IF SOMETHING WENT WRONG.
#
- id: ssl_expiry_notification
  alias: 'SSL expiry notification'
  trigger:
    platform: numeric_state
    entity_id: sensor.ssl_certificate_expiry
    below: 21
  action:
    service: script.turn_on
    entity_id: script.notifica_evento
    data:
      variables:
        title: '*CERTIFICADO SSL*'
        message: >
          >>> EVENTO: El certificado SSL expira en {{ states('sensor.ssl_certificate_expiry') }}


- id: alarma_prosegur_device_check
  alias: 'Prosegur Device Tracking Check'
  trigger:
    platform: state
    entity_id: device_tracker.prosegur
    from: 'home'
    to: 'away'
    for: '05:00:00'
  action:
    - service: script.turn_on
      entity_id: script.notifica_alarma
      data:
        variables:
          title: '*ALARMA*'
          message: >
            >>> URGENTE HA: Prosegur No Responde (NMAP)

#-----------------------------------------------------------------------------#
#                                                                             #
# REGLAS DE CONTROL DE LUCES Y ALUMBRADO                                      #
#                                                                             #
#-----------------------------------------------------------------------------#

- id: L01_luces_on_entrada_on_sensor
  alias: 'L01 Luces On Entrada Según Sensor'
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0001e55903
      to: 'on'
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d00022b393c
      to: 'on'
  condition:
    condition: or  # 'when dark' condition: either after sunset or before sunrise
    conditions:
      - condition: sun
        after: sunset
        after_offset: "-1:00:00"
      - condition: sun
        before: sunrise
        before_offset: "+3:00:00"
  #condition:
    #condition: numeric_state
    #entity_id: sensor.temperature
    #below: 10
    #condition: template
    #value_template: '{{ states.sensor.illumination_158d0001e55903.state < 10 }}'
  action:
    - service: light.turn_on
      entity_id: light.hue_entrada
      data:
        brightness: 120
        rgb_color: [255, 0, 0]

- id: L02_luz_off_entrada_off_sensor
  alias: 'L02 Luces Off Entrada Según Sensor'
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0001e55903
      to: 'off'
      for:
        minutes: 5
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d00022b393c
      to: 'off'
      for:
        minutes: 5
  action:
    - service: light.turn_off
      entity_id: light.hue_entrada

- id: L03_luces_on_exterior_sunset
  alias: 'L03 Luces On Exterior Puesta Sol +15m'
  trigger:
    - platform: sun
      event: sunset
      offset: "+00:15:00"
    #- condition: time
    #  before: '23:59:00'
  action:
    - service: switch.turn_on
      entity_id: switch.wall_switch_right_158d0002236e75
    # Notifica Evento
    - service: script.turn_on
      entity_id: script.notifica_evento
      data:
        variables:
          title: '*LUCES: ON*'
          message: >
            >>> EVENTO: Puesta de sol hace 15min

            >>> LUCES: Alumbrado Exterior ON

- id: L04_luces_off_exterior_family_home
  alias: 'L04 Luces Off Exterior Si Family Home +05m'
  trigger:
    # Todos duermen y están en casa
    - platform: state
      entity_id: binary_sensor.family_all_home
      from: 'off'
      to: 'on'
    - platform: time
      at: '00:01:00'
  condition:
    condition: and
    conditions:
      - condition: time
        after: '23:59:00'
      # Están todos en casa
      - condition: state
        entity_id: binary_sensor.family_all_home
        state: 'on'
  action:
    - delay: 0:05
    - service: switch.turn_off
      entity_id: switch.wall_switch_right_158d0002236e75
    # Notifica a Familia
    - service: script.turn_on
      entity_id: script.notifica_evento
      data:
        variables:
          title: '*LUCES: OFF*'
          message: >
            >>> EVENTO: Es Medianoche y todos en casa

            >>> LUCES: Alumbrado Exterior Off

- id: L05_luces_off_exterior_sunrise
  alias: 'L05 Luces Off Exterior Amanecer -4h'
  trigger:
    - platform: sun
      event: sunrise
      offset: "-04:00:00"
  condition:
    condition: state
    entity_id: switch.wall_switch_right_158d0002236e75
    state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.wall_switch_right_158d0002236e75
    # Notifica a Familia
    - service: script.turn_on
      entity_id: script.notifica_evento
      data:
        variables:
          title: '*LUCES: OFF*'
          message: >
            >>> EVENTO: Amanecer en 4 horas

            >>> LUCES: Alumbrado Exterior Off

- id: L06_luces_on_salon_sunset
  alias: 'L06 Luces On Salon Puesta Sol -1h'
  trigger:
    - platform: sun
      event: sunset
      offset: "-01:00:00"
  condition:
    # Hay alguien en casa
    condition: state
    entity_id: group.family_home_grp
    state: 'on'
  action:
    - service: light.turn_on
      entity_id: light.room_salon_tv
    # Notifica a Familia
    - service: script.turn_on
      entity_id: script.notifica_evento
      data:
        variables:
          title: '*LUCES: ON*'
          message: >
            >>> EVENTO: El sol se pone en 1hora

            >>> LUCES: Luces Salón On

- id: L07_luces_off_midnight
  alias: 'L07 Luces Off si Medianoche'
  trigger:
    - platform: time
      at: "00:00:00"
  action:
    # Script Luces Apagado Interior Casa
    - service: script.turn_on
      entity_id: script.luces_off
    # Notifica a Familia
    - service: script.turn_on
      entity_id: script.notifica_evento
      data:
        variables:
          title: '*LUCES: OFF*'
          message: >
            >>> EVENTO: Medianoche

            >>> LUCES: Luces Interior Off

- id: L08_luces_off_home_sunrise
  alias: 'L08 Luces Off Al Amanecer'
  trigger:
    - platform: sun
      event: sunrise
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: group.luces_salon_grp
        state: 'on'
      - condition: state
        entity_id: group.luces_estudio_grp
        state: 'on'
      - condition: state
        entity_id: group.luces_cocina_grp
        state: 'on'
  action:
    # Script Luces Apagado Interior Casa
    - service: script.turn_on
      entity_id: script.luces_off
    # Notifica a Familia
    - service: script.turn_on
      entity_id: script.notifica_evento
      data:
        variables:
          title: '*LUCES: OFF*'
          message: >
            >>> EVENTO: Luces encendidas al amanecer

            >>> LUCES: Apagado total