#
# AGUSTIN: Control Presencia => Booleean input_boolean.acchome
#
- id: update_tracker_to_not_home_aac
  alias: 'AAC to Not Home'
  initial_state: True
  trigger:
    - platform: state
      entity_id:
        - device_tracker.aac_ios
        - device_tracker.aac_iphone_owntrack
        - device_tracker.b8b52a3bf0384e72a268705d9b06e496 #AAC
      to: 'not_home'
    - platform: state
      entity_id: device_tracker.aac_iphone_nmap
      to: 'not_home'
      for: '00:07:00'
  condition:
    condition: state
    entity_id: input_boolean.aachome
    state: 'on'
  action:
    service: homeassistant.turn_off
    entity_id: input_boolean.aachome

- id: update_tracker_to_home_aac
  alias: 'AAC to Home'
  initial_state: True
  trigger:
    - platform: state
      entity_id:
        - device_tracker.aac_ios
        - device_tracker.aac_iphone_nmap
        - device_tracker.aac_iphone_owntrack
        - device_tracker.b8b52a3bf0384e72a268705d9b06e496 #AAC
      to: 'home'
  condition:
    condition: state
    entity_id: input_boolean.aachome
    state: 'off'
  action:
    service: homeassistant.turn_on
    entity_id: input_boolean.aachome

#
# MALEN: Control Presencia =>  input_boolean.mfchome
#
- id: update_tracker_to_not_home_mfc
  alias: 'MFC to Not Home'
  initial_state: True
  trigger:
    - platform: state
      entity_id:
        - device_tracker.mfc_ios
        - device_tracker.mfc_iphone_owntrack
        - device_tracker.e3c67d6b51bf445ba241a0045bfe0222 # MFC
      to: 'not_home'
    - platform: state
      entity_id: device_tracker.mfc_iphone_nmap
      to: 'not_home'
      for: '00:07:00'
  condition:
    condition: state
    entity_id: input_boolean.mfchome
    state: 'on'
  action:
    service: homeassistant.turn_off
    entity_id: input_boolean.mfchome

- id: update_tracker_to_home_mfc
  alias: 'MFC to Home'
  initial_state: True
  trigger:
    - platform: state
      entity_id:
        - device_tracker.mfc_ios
        - device_tracker.mfc_iphone_nmap
        - device_tracker.mfc_iphone_owntrack_mfc
        - device_tracker.e3c67d6b51bf445ba241a0045bfe0222 #MFC
      to: 'home'
  condition:
    condition: state
    entity_id: input_boolean.mfchome
    state: 'off'
  action:
    service: homeassistant.turn_on
    entity_id: input_boolean.mfchome
#
# PALOMA: Control Presencia => input_boolean.pafhome
#
- id: update_tracker_to_not_home_paf
  alias: 'PAF to Not Home'
  initial_state: True
  trigger:
    - platform: state
      entity_id: device_tracker.paf_iphone_nmap
      to: 'not_home'
      for: '00:07:00'
    - platform: state
      entity_id: device_tracker.93e3d52336a54d4d898b204abdf3ee94 #PAF
      to: 'not_home'
  condition:
    condition: state
    entity_id: input_boolean.pafhome
    state: 'on'
  action:
    service: homeassistant.turn_off
    entity_id: input_boolean.pafhome

- id: update_tracker_to_home_paf
  alias: 'PAF to Home'
  initial_state: True
  trigger:
    - platform: state
      entity_id:
        - device_tracker.paf_iphone_nmap
        - device_tracker.93e3d52336a54d4d898b204abdf3ee94 #PAF
        #- device_tracker.paf_iphone_owntrack
      to: 'home'
  condition:
    condition: state
    entity_id: input_boolean.pafhome
    state: 'off'
  action:
    service: homeassistant.turn_on
    entity_id: input_boolean.pafhome
#
# AGU: Control Presencia => input_boolean.aafhome
#
- id: update_tracker_to_not_home_aaf
  alias: 'AAF to Not Home'
  initial_state: True
  trigger:
    - platform: state
      entity_id: device_tracker.aaf_iphone_nmap
      to: 'not_home'
      for: '00:10:00'
    - platform: state
      entity_id: device_tracker.bef743fa74f2464ba458612ad3e1c195
      to: 'not_home'
  condition:
    condition: state
    entity_id: input_boolean.aafhome
    state: 'on'
  action:
    service: homeassistant.turn_off
    entity_id: input_boolean.aafhome

- id: update_tracker_to_home_aaf
  alias: 'AAF to Home'
  initial_state: True
  trigger:
    - platform: state
      entity_id:
        - device_tracker.aaf_iphone_nmap
        - device_tracker.bef743fa74f2464ba458612ad3e1c195
      to: 'home'
  condition:
    condition: state
    entity_id: input_boolean.aafhome
    state: 'off'
  action:
    service: homeassistant.turn_on
    entity_id: input_boolean.aafhome

#
# LUCES: Apagado/Encendido general según groups.family
#
- id: switch_off_lights_family_not_home
  alias: 'Apaga Luces Si Family Out'
  trigger:
    platform: state
    entity_id: group.family_home
    from: 'on'
    to: 'off'
  action:
    service: light.turn_off
    entity_id: group.all_lights

- id: switch_on_entrada_family_get_home
  alias: 'Endiende Piloto Si Family Home'
  trigger:
    - platform: state
      entity_id: group.family_home
      from: 'off'
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: sun
        after: sunset
      - condition: time
        before: '00:00:00'
  action:
    service: light.turn_on
    entity_id: light.hue_cocina
