
#-----------------------------------------------------------------------------#
#                                                                             #
# FAMILY TRACKING Control Home/Away                                           #
#                                                                             #
#-----------------------------------------------------------------------------#

#
# AGUSTIN: Control Presencia => Booleean input_boolean.acchome
#
- id: update_tracker_to_not_home_aac
  alias: 'Home 2 Away AAC'
  initial_state: True
  trigger:
    - platform: state
      entity_id:
        - device_tracker.aac_ios
        - device_tracker.aac_iphone_owntrack
        - device_tracker.b8b52a3bf0384e72a268705d9b06e496 #AAC
      to: 'not_home'
  condition:
    condition: state
    entity_id: input_boolean.home_aac
    state: 'on'
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.home_aac
    - service: input_select.select_option
      data:
        entity_id: input_select.home_last_change
        option: Agustín

- id: update_nmap_to_not_home_aac
  alias: 'Home 2 Away AAC NMAP'
  initial_state: True
  trigger:
    - platform: state
      entity_id: device_tracker.aac_iphone_nmap
      to: 'not_home'
      for: '00:10:00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.home_aac
        state: 'on'
      - condition: time
        after: '08:00:00'
      - condition: time
        before: '23:59:00'
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.home_aac
    - service: input_select.select_option
      data:
        entity_id: input_select.home_last_change
        option: Agustín

- id: update_tracker_to_home_aac
  alias: 'Away to Home AAC'
  initial_state: True
  trigger:
    - platform: state
      entity_id:
        - device_tracker.aac_ios
        - device_tracker.aac_iphone_nmap
        - device_tracker.aac_iphone_owntrack
        - device_tracker.b8b52a3bf0384e72a268705d9b06e496 #AAC
      to: 'home'
  condition:
    condition: state
    entity_id: input_boolean.home_aac
    state: 'off'
  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.home_aac
    - service: input_select.select_option
      data:
        entity_id: input_select.home_last_change
        option: Agustín


#
# MALEN: Control Presencia =>  input_boolean.home_mfc
#
- id: update_tracker_to_not_home_mfc
  alias: 'Home 2 Away MFC'
  initial_state: True
  trigger:
    - platform: state
      entity_id:
        - device_tracker.mfc_ios
        - device_tracker.mfc_iphone_owntrack
        - device_tracker.e3c67d6b51bf445ba241a0045bfe0222 # MFC
      to: 'not_home'
  condition:
    condition: state
    entity_id: input_boolean.home_mfc
    state: 'on'
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.home_mfc
    - service: input_select.select_option
      data:
        entity_id: input_select.home_last_change
        option: Malen

- id: update_nmap_to_not_home_mfc
  alias: 'Home 2 Away MFC NMAP'
  initial_state: True
  trigger:
    - platform: state
      entity_id: device_tracker.mfc_iphone_nmap
      to: 'not_home'
      for: '00:10:00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.home_mfc
        state: 'on'
      - condition: time
        after: '08:00:00'
      - condition: time
        before: '23:59:00'
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.home_mfc
    - service: input_select.select_option
      data:
        entity_id: input_select.home_last_change
        option: Malen

- id: update_tracker_to_home_mfc
  alias: 'Away to Home MFC'
  initial_state: True
  trigger:
    - platform: state
      entity_id:
        - device_tracker.mfc_ios
        - device_tracker.mfc_iphone_nmap
        - device_tracker.mfc_iphone_owntrack_mfc
        - device_tracker.e3c67d6b51bf445ba241a0045bfe0222 #MFC
      to: 'home'
  condition:
    condition: state
    entity_id: input_boolean.home_mfc
    state: 'off'
  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.home_mfc
    - service: input_select.select_option
      data:
        entity_id: input_select.home_last_change
        option: Malen
#
# PALOMA: Control Presencia => input_boolean.home_paf
#
- id: update_tracker_to_not_home_paf
  alias: 'Home 2 Away PAF'
  initial_state: True
  trigger:
    - platform: state
      entity_id: device_tracker.93e3d52336a54d4d898b204abdf3ee94 #PAF
      to: 'not_home'
  condition:
    condition: state
    entity_id: input_boolean.home_paf
    state: 'on'
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.home_paf
    - service: input_select.select_option
      data:
        entity_id: input_select.home_last_change
        option: Paloma

- id: update_nmap_to_not_home_paf
  alias: 'Home 2 Away PAF NMAP'
  initial_state: True
  trigger:
    - platform: state
      entity_id: device_tracker.paf_iphone_nmap
      to: 'not_home'
      for: '00:10:00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.home_paf
        state: 'on'
      - condition: time
        after: '08:00:00'
      - condition: time
        before: '23:59:00'
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.home_paf
    - service: input_select.select_option
      data:
        entity_id: input_select.home_last_change
        option: Paloma

- id: update_tracker_to_home_paf
  alias: 'Away to Home PAF'
  initial_state: True
  trigger:
    - platform: state
      entity_id:
        - device_tracker.paf_iphone_nmap
        - device_tracker.93e3d52336a54d4d898b204abdf3ee94 #PAF
      to: 'home'
  condition:
    condition: state
    entity_id: input_boolean.home_paf
    state: 'off'
  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.home_paf
    - service: input_select.select_option
      data:
        entity_id: input_select.home_last_change
        option: Paloma
#
# AGU: Control Presencia => input_boolean.agu
#
- id: update_tracker_to_not_home_aaf
  alias: 'Home 2 Away AAF'
  initial_state: True
  trigger:
    - platform: state
      entity_id: device_tracker.bef743fa74f2464ba458612ad3e1c195
      to: 'not_home'
  condition:
    condition: state
    entity_id: input_boolean.home_aaf
    state: 'on'
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.home_aaf
    - service: input_select.select_option
      data:
        entity_id: input_select.home_last_change
        option: Agu

- id: update_nmap_to_not_home_aaf
  alias: 'Home 2 Away AAF NMAP'
  initial_state: True
  trigger:
    - platform: state
      entity_id: device_tracker.aaf_iphone_nmap
      to: 'not_home'
      for: '00:10:00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.home_aaf
        state: 'on'
      - condition: time
        after: '08:00:00'
      - condition: time
        before: '23:59:00'
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.home_aaf
    - service: input_select.select_option
      data:
        entity_id: input_select.home_last_change
        option: Agu

- id: update_tracker_to_home_aaf
  alias: 'Away to Home AAF'
  initial_state: True
  trigger:
    - platform: state
      entity_id:
        - device_tracker.aaf_iphone_nmap
        - device_tracker.bef743fa74f2464ba458612ad3e1c195
      to: 'home'
  condition:
    condition: state
    entity_id: input_boolean.home_aaf
    state: 'off'
  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.home_aaf
    - service: input_select.select_option
      data:
        entity_id: input_select.home_last_change
        option: Agu

#-----------------------------------------------------------------------------#
#                                                                             #
# FAMILY AT HOME: Control Home/Away                                           #
#                                                                             #
#-----------------------------------------------------------------------------#

- id: family_away
  alias: 'Family Away'
  trigger:
    platform: state
    entity_id: group.family_home_grp
    from: 'on'
    to: 'off'
  action:
    # Script Luces Apagado Total
    - service: script.turn_on
      entity_id: script.luces_off_family_away
    # Servicio Alarma Armado Total
    - service: alarm_control_panel.alarm_arm_away
      data:
        entity_id: alarm_control_panel.ha
        code: !secret alarm_control_code
    # Notifica a Familia NADIE en Casa
    - service: script.turn_on
      entity_id: script.notifica_evento
      data:
        variables:
          title: '[FAMILY@HOME]: NO'
          message: >
            >>> EVENTO: Último en Salir {{ states('input_select.home_last_change') }}

            >>> LUCES: Luces interior Off

            >>> ALARMA: Armado Total

- id: family_at_home
  alias: 'Family at Home'
  trigger:
    - platform: state
      entity_id: group.family_home_grp
      from: 'off'
      to: 'on'
  action:
    # Script encendido Luz piloto si es de noche
    - service: script.turn_on
      entity_id: script.luces_on_family_home
    # Servicio Alarma Armado Total
    - service: alarm_control_panel.alarm_disarm
      data:
        entity_id: alarm_control_panel.ha
        code: !secret alarm_control_code
    # Notifica a Familia Alguien en Casa
    - service: script.turn_on
      entity_id: script.notifica_evento
      data:
        variables:
          title: '*FAMILY@HOME: SI*'
          message: >
            >>> EVENTO: Ha entrado {{ states('input_select.home_last_change') }}

            >>> LUCES: Luces entrada On

            >>> ALARMA: Desarmado

#-----------------------------------------------------------------------------#
#                                                                             #
# REGLAS DE CONTROL DE LUCES Y ALUMBRADO                                      #
#                                                                             #
#-----------------------------------------------------------------------------#

- id: luces_exterior_on_sunset
  alias: 'Luces Exterior On Sunset offset+15m'
  trigger:
    - platform: sun
      event: sunset
      offset: "+00:15:00"
    #- condition: time
    #  before: '23:59:00'
  action:
    - service: switch.turn_on
      entity_id: switch.wall_switch_right_158d0002236e75
    # Notifica Evento
    - service: script.turn_on
      entity_id: script.notifica_evento
      data:
        variables:
          title: '*LUCES: ON*'
          message: >
            >>> EVENTO: Puesta de sol hace 15min

            >>> LUCES: Alumbrado Exterior ON

- id: luces_exterior_off_family_home
  alias: 'Luces Exterior Off Family Home delay 10m'
  trigger:
    - platform: state
      entity_id: group.family_home_grp
      from: 'off'
      to: 'on'
    - platform: time
      at: '00:01:00'
  condition:
    condition: and
    conditions:
      - condition: time
        after: '00:00:00'
      - condition: state
        entity_id: group.family_home_grp
        state: 'on'
  action:
    - delay: 0:05
    - service: switch.turn_off
      entity_id: switch.wall_switch_right_158d0002236e75
    # Notifica a Familia
    - service: script.turn_on
      entity_id: script.notifica_evento
      data:
        variables:
          title: '*LUCES: OFF*'
          message: >
            >>> EVENTO: Medianoche y Family@Home

            >>> LUCES: Alumbrado Exterior Off

- id: sunrise_luces_exterior_off
  alias: 'Luces Exterior Off Sunrise offset 3h'
  trigger:
    - platform: sun
      event: sunrise
      offset: "-03:00:00"
  condition:
    condition: state
    entity_id: switch.wall_switch_right_158d0002236e75
    state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.wall_switch_right_158d0002236e75
    # Notifica a Familia
    - service: script.turn_on
      entity_id: script.notifica_evento
      data:
        variables:
          title: '*LUCES: OFF*'
          message: >
            >>> EVENTO: Amanecer en 2 horas

            >>> LUCES: Alumbrado Exterior Off

- id: luces_salon_on_sunset
  alias: 'Luces Salon On Sunset Offset 30m'
  trigger:
    - platform: sun
      event: sunset
      offset: "-00:30:00"
  condition:
    condition: state
    entity_id: group.family_home_grp
    state: 'on'
  action:
    - service: light.turn_on
      entity_id: light.room_salon_tv
    # Notifica a Familia
    - service: script.turn_on
      entity_id: script.notifica_evento
      data:
        variables:
          title: '*LUCES: ON*'
          message: >
            >>> EVENTO: El sol se pone en 30min

            >>> LUCES: Luces Salón ON

- id: sunrise_luces_salon_off
  alias: 'Luces Salon Off Sunrise'
  trigger:
    - platform: time
      at: "00:00:00"
  action:
    - service: switch.turn_off
      entity_id: switch.wall_switch_right_158d0002236e75
    # Notifica a Familia
    - service: script.turn_on
      entity_id: script.notifica_evento
      data:
        variables:
          title: '*LUCES: OFF*'
          message: >
            >>> EVENTO: Medianoche

            >>> LUCES: Luces Salón Off

- id: luz_entrada_on_sensor
  alias: 'Luces Entrada On Sensor'
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0001e55903
      to: 'on'
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d00022b393c
      to: 'on'
  condition:
    condition: or  # 'when dark' condition: either after sunset or before sunrise
    conditions:
      - condition: sun
        after: sunset
        after_offset: "-1:00:00"
      - condition: sun
        before: sunrise
        before_offset: "+3:00:00"
  #condition:
    #condition: numeric_state
    #entity_id: sensor.temperature
    #below: 10
    #condition: template
    #value_template: '{{ states.sensor.illumination_158d0001e55903.state < 10 }}'
  action:
    - service: light.turn_on
      entity_id: light.hue_entrada
      data:
        brightness: 120
        rgb_color: [255, 0, 0]

- id: luz_entrada_off_sensor
  alias: 'Luces Entrada Off Sensor'
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0001e55903
      to: 'off'
      for:
        minutes: 5
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d00022b393c
      to: 'off'
      for:
        minutes: 5
  action:
    - service: light.turn_off
      entity_id: light.hue_entrada

#-----------------------------------------------------------------------------#
#                                                                             #
# ALARMA: Armado y Control de la Alarma                                       #
#                                                                             #
#-----------------------------------------------------------------------------#

- id: alarma_prosegur_device_check
  alias: 'Prosegur Device Tracking Check'
  trigger:
    platform: state
    entity_id: device_tracker.prosegur
    from: 'home'
    to: 'away'
    for: '05:00:00'
  action:
    - service: script.turn_on
      entity_id: script.notifica_alarma
      data:
        variables:
          title: '*ALARMA*'
          message: >
            >>> URGENTE HA: Prosegur No Responde (NMAP)


- id: alarma_boton_panico_on
  alias: 'Alarma Boton Panico On'
  trigger:
    platform: state
    entity_id: input_boolean.alarm_mode
    from: 'off'
    to: 'on'
  action:
    - service: xiaomi_aqara.play_ringtone
      data:
        gw_mac: 78:11:DC:B7:88:FA
        ringtone_id: 1
        ringtone_vol: 100
    - service: script.turn_on
      entity_id: script.notifica_alarma
      data:
        variables:
          title: '*ALARMA*'
          message: >
            >>> URGENTE: ALARMA EN CASA

- id: alarma_boton_panico_off
  alias: 'Alarma Boton Panico Off'
  trigger:
    platform: state
    entity_id: input_boolean.alarm_mode
    from: 'on'
    to: 'off'
  action:
    - service: xiaomi_aqara.stop_ringtone
      data:
        gw_mac: 78:11:DC:B7:88:FA
    - service: script.turn_on
      entity_id: script.notifica_alarma
      data:
        variables:
          title: '*ALARMA*'
          message: >
            >>> URGENTE: DESARMADO


- id: alarma_away_intrusion
  alias: 'Alarma Away Intrusion'
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0001e55903
      to: 'on'
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d00022b393c
      to: 'on'
  condition:
    - condition: state
      entity_id: alarm_control_panel.ha
      state: armed_away
  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.alarm_mode
    - service: xiaomi_aqara.play_ringtone
      data:
        gw_mac: 78:11:DC:B7:88:FA
        ringtone_id: 1
        ringtone_vol: 100
    # Script Notificación Alarma
    - service: script.turn_on
      entity_id: script.notifica_alarma
      data:
        variables:
          title: '*ALARMA*'
          message: >
            >>> URGENTE: ALARMA EN CASA

            >>> ZONA: Sensor Entrada

            >>> SIRENA: Sirena sonando
    # Script Envio Fotos Cámaras Telegram
    - service: script.turn_on
      entity_id: script.telegram_alarm_send_photo

#-----------------------------------------------------------------------------#
#                                                                             #
# CONTROL DEL SISTEMA                                                         #
#                                                                             #
#-----------------------------------------------------------------------------#

#
# CERTBOT SSL CERTIFICATE: ALERT TO WARN US IF SOMETHING WENT WRONG.
#
- id: ssl_expiry_notification
  alias: 'SSL expiry notification'
  trigger:
    platform: numeric_state
    entity_id: sensor.ssl_certificate_expiry
    below: 21
  action:
    service: script.turn_on
    entity_id: script.notifica_evento
    data:
      variables:
        title: 'CERTIFICADO SSL'
        message: >
          >>> EVENTO: El certificado SSL expira en {{ states('sensor.ssl_certificate_expiry') }}
