#
# AGUSTIN: Control Presencia => Booleean input_boolean.acchome
#
- id: update_tracker_to_not_home_aac
  alias: 'Home 2 Away AAC'
  initial_state: True
  trigger:
    - platform: state
      entity_id:
        - device_tracker.aac_ios
        - device_tracker.aac_iphone_owntrack
        - device_tracker.b8b52a3bf0384e72a268705d9b06e496 #AAC
      to: 'not_home'
  condition:
    condition: state
    entity_id: input_boolean.home_aac
    state: 'on'
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.home_aac
    - service: input_select.select_option
      data:
        entity_id: input_select.home_last_change
        option: Agustín

- id: update_nmap_to_not_home_aac
  alias: 'Home 2 Away AAC NMAP'
  initial_state: True
  trigger:
    - platform: state
      entity_id: device_tracker.aac_iphone_nmap
      to: 'not_home'
      for: '00:10:00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.home_aac
        state: 'on'
      - condition: time
        after: '08:00:00'
      - condition: time
        before: '23:59:00'
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.home_aac
    - service: input_select.select_option
      data:
        entity_id: input_select.home_last_change
        option: Agustín

- id: update_tracker_to_home_aac
  alias: 'Away to Home AAC'
  initial_state: True
  trigger:
    - platform: state
      entity_id:
        - device_tracker.aac_ios
        - device_tracker.aac_iphone_nmap
        - device_tracker.aac_iphone_owntrack
        - device_tracker.b8b52a3bf0384e72a268705d9b06e496 #AAC
      to: 'home'
  condition:
    condition: state
    entity_id: input_boolean.home_aac
    state: 'off'
  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.home_aac
    - service: input_select.select_option
      data:
        entity_id: input_select.home_last_change
        option: Agustín


#
# MALEN: Control Presencia =>  input_boolean.home_mfc
#
- id: update_tracker_to_not_home_mfc
  alias: 'Home 2 Away MFC'
  initial_state: True
  trigger:
    - platform: state
      entity_id:
        - device_tracker.mfc_ios
        - device_tracker.mfc_iphone_owntrack
        - device_tracker.e3c67d6b51bf445ba241a0045bfe0222 # MFC
      to: 'not_home'
  condition:
    condition: state
    entity_id: input_boolean.home_mfc
    state: 'on'
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.home_mfc
    - service: input_select.select_option
      data:
        entity_id: input_select.home_last_change
        option: Malen

- id: update_nmap_to_not_home_mfc
  alias: 'Home 2 Away MFC NMAP'
  initial_state: True
  trigger:
    - platform: state
      entity_id: device_tracker.mfc_iphone_nmap
      to: 'not_home'
      for: '00:10:00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.home_mfc
        state: 'on'
      - condition: time
        after: '08:00:00'
      - condition: time
        before: '23:59:00'
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.home_mfc
    - service: input_select.select_option
      data:
        entity_id: input_select.home_last_change
        option: Malen

- id: update_tracker_to_home_mfc
  alias: 'Away to Home MFC'
  initial_state: True
  trigger:
    - platform: state
      entity_id:
        - device_tracker.mfc_ios
        - device_tracker.mfc_iphone_nmap
        - device_tracker.mfc_iphone_owntrack_mfc
        - device_tracker.e3c67d6b51bf445ba241a0045bfe0222 #MFC
      to: 'home'
  condition:
    condition: state
    entity_id: input_boolean.home_mfc
    state: 'off'
  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.home_mfc
    - service: input_select.select_option
      data:
        entity_id: input_select.home_last_change
        option: Malen
#
# PALOMA: Control Presencia => input_boolean.home_paf
#
- id: update_tracker_to_not_home_paf
  alias: 'Home 2 Away PAF'
  initial_state: True
  trigger:
    - platform: state
      entity_id: device_tracker.93e3d52336a54d4d898b204abdf3ee94 #PAF
      to: 'not_home'
  condition:
    condition: state
    entity_id: input_boolean.home_paf
    state: 'on'
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.home_paf
    - service: input_select.select_option
      data:
        entity_id: input_select.home_last_change
        option: Paloma

- id: update_nmap_to_not_home_paf
  alias: 'Home 2 Away PAF NMAP'
  initial_state: True
  trigger:
    - platform: state
      entity_id: device_tracker.paf_iphone_nmap
      to: 'not_home'
      for: '00:10:00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.home_paf
        state: 'on'
      - condition: time
        after: '08:00:00'
      - condition: time
        before: '23:59:00'
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.home_paf
    - service: input_select.select_option
      data:
        entity_id: input_select.home_last_change
        option: Paloma

- id: update_tracker_to_home_paf
  alias: 'Away to Home PAF'
  initial_state: True
  trigger:
    - platform: state
      entity_id:
        - device_tracker.paf_iphone_nmap
        - device_tracker.93e3d52336a54d4d898b204abdf3ee94 #PAF
      to: 'home'
  condition:
    condition: state
    entity_id: input_boolean.home_paf
    state: 'off'
  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.home_paf
    - service: input_select.select_option
      data:
        entity_id: input_select.home_last_change
        option: Paloma
#
# AGU: Control Presencia => input_boolean.agu
#
- id: update_tracker_to_not_home_aaf
  alias: 'Home 2 Away AAF'
  initial_state: True
  trigger:
    - platform: state
      entity_id: device_tracker.bef743fa74f2464ba458612ad3e1c195
      to: 'not_home'
  condition:
    condition: state
    entity_id: input_boolean.home_aaf
    state: 'on'
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.home_aaf
    - service: input_select.select_option
      data:
        entity_id: input_select.home_last_change
        option: Agu

- id: update_nmap_to_not_home_aaf
  alias: 'Home 2 Away AAF NMAP'
  initial_state: True
  trigger:
    - platform: state
      entity_id: device_tracker.aaf_iphone_nmap
      to: 'not_home'
      for: '00:10:00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.home_aaf
        state: 'on'
      - condition: time
        after: '08:00:00'
      - condition: time
        before: '23:59:00'
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.home_aaf
    - service: input_select.select_option
      data:
        entity_id: input_select.home_last_change
        option: Agu

- id: update_tracker_to_home_aaf
  alias: 'Away to Home AAF'
  initial_state: True
  trigger:
    - platform: state
      entity_id:
        - device_tracker.aaf_iphone_nmap
        - device_tracker.bef743fa74f2464ba458612ad3e1c195
      to: 'home'
  condition:
    condition: state
    entity_id: input_boolean.home_aaf
    state: 'off'
  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.home_aaf
    - service: input_select.select_option
      data:
        entity_id: input_select.home_last_change
        option: Agu

#
# FAMILY AT HOME: Control Home/Away
#
- id: family_away
  alias: 'Family Away'
  trigger:
    platform: state
    entity_id: group.family_home_grp
    from: 'on'
    to: 'off'
  action:
    # Notifica a Familia NADIE en Casa
    - service: script.turn_on
      entity_id: script.mensaje_family
      data:
        variables:
          title: 'FAMILY at HOME: <NO>'
          message: >
            >>> Evento: {{ states('input_select.home_last_change') }}
          #>>> {{ trigger.event }}
          #>>> {{ trigger.to_state.state }}
          #{{ states('trigger.to_state') }}
    # Script Luces Apagado Total
    - service: script.turn_on
      entity_id: script.luces_off_family_away

- id: family_at_home
  alias: 'Family at Home'
  trigger:
    - platform: state
      entity_id: group.family_home_grp
      from: 'off'
      to: 'on'
  action:
    # Notifica a Familia NADIE en Casa
    - service: script.turn_on
      entity_id: script.mensaje_family
      data:
        variables:
          title: 'FAMILY at HOME: <SI>'
          message: >
            >>> Evento: {{ states('input_select.home_last_change') }}
    # Script encendido Luz piloto si es de noche y antes 00:00
    - service: script.turn_on
      entity_id: script.luces_on_family_home

#
# ALARMA: Armado y Control de la Alarma
#
- id: alarm_prosegur_device_check
  alias: 'Prosegur Device Tracking Check'
  trigger:
    platform: state
    entity_id: device_tracker.prosegur
    from: 'home'
    to: 'away'
    for: '05:00:00'
  action:
    - service: script.turn_on
      entity_id: script.mensaje_family
      data:
        variables:
          title: '[ALARMA PROSEGUR]'
          message: >
            >>> URGENTE HA: Prosegur No Responde (NMAP)

- id: alarm_sirena_on_notification
  alias: 'Alarm  Notification'
  trigger:
    platform: state
    entity_id: input_boolean.alarm_mode
    from: 'off'
    to: 'on'
  action:
    - service: script.turn_on
      entity_id: script.mensaje_family
      data:
        variables:
          title: '[ALARMA]'
          message: >
            >>> URGENTE HA: ALARMA ACTIVADA
    - service: xiaomi_aqara.play_ringtone
      data:
        gw_mac: 78:11:DC:B7:88:FA
        ringtone_id: 1
        ringtone_vol: 100

- id: alarm_sirena_off_notification
  alias: 'Alarm Test Notification'
  trigger:
    platform: state
    entity_id: input_boolean.alarm_mode
    from: 'on'
    to: 'off'
  action:
    - service: script.turn_on
      entity_id: script.mensaje_family
      data:
        variables:
          title: '[ALARMA]'
          message: >
            >>> URGENTE HA: ALARMA DESACTIVADA
    - service: xiaomi_aqara.stop_ringtone
      data:
        gw_mac: 78:11:DC:B7:88:FA

    #- service: script.turn_on
    #entity_id: script.telegram_alarm_send_photo

