#
# AGUSTIN: Control Presencia => Booleean input_boolean.acchome
#
- id: update_tracker_to_not_home_aac
  alias: 'Home 2 Away AAC'
  initial_state: True
  trigger:
    - platform: state
      entity_id:
        - device_tracker.aac_ios
        - device_tracker.aac_iphone_owntrack
        - device_tracker.b8b52a3bf0384e72a268705d9b06e496 #AAC
      to: 'not_home'
  condition:
    condition: state
    entity_id: input_boolean.home_aac
    state: 'on'
  action:
    service: homeassistant.turn_off
    entity_id: input_boolean.home_aac

- id: update_nmap_to_not_home_aac
  alias: 'Home 2 Away AAC NMAP'
  initial_state: True
  trigger:
    - platform: state
      entity_id: device_tracker.aac_iphone_nmap
      to: 'not_home'
      for: '00:10:00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.home_aac
        state: 'on'
      - condition: time
        after: '08:00:00'
      - condition: time
        before: '23:59:00'
  action:
    service: homeassistant.turn_off
    entity_id: input_boolean.home_aac

- id: update_tracker_to_home_aac
  alias: 'Away to Home AAC'
  initial_state: True
  trigger:
    - platform: state
      entity_id:
        - device_tracker.aac_ios
        - device_tracker.aac_iphone_nmap
        - device_tracker.aac_iphone_owntrack
        - device_tracker.b8b52a3bf0384e72a268705d9b06e496 #AAC
      to: 'home'
  condition:
    condition: state
    entity_id: input_boolean.home_aac
    state: 'off'
  action:
    service: homeassistant.turn_on
    entity_id: input_boolean.home_aac

#
# MALEN: Control Presencia =>  input_boolean.home_mfc
#
- id: update_tracker_to_not_home_mfc
  alias: 'Home 2 Away MFC'
  initial_state: True
  trigger:
    - platform: state
      entity_id:
        - device_tracker.mfc_ios
        - device_tracker.mfc_iphone_owntrack
        - device_tracker.e3c67d6b51bf445ba241a0045bfe0222 # MFC
      to: 'not_home'
  condition:
    condition: state
    entity_id: input_boolean.home_mfc
    state: 'on'
  action:
    service: homeassistant.turn_off
    entity_id: input_boolean.home_mfc

- id: update_nmap_to_not_home_mfc
  alias: 'Home 2 Away MFC NMAP'
  initial_state: True
  trigger:
    - platform: state
      entity_id: device_tracker.mfc_iphone_nmap
      to: 'not_home'
      for: '00:10:00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.home_mfc
        state: 'on'
      - condition: time
        after: '08:00:00'
      - condition: time
        before: '23:59:00'
  action:
    service: homeassistant.turn_off
    entity_id: input_boolean.home_mfc

- id: update_tracker_to_home_mfc
  alias: 'Away to Home MFC'
  initial_state: True
  trigger:
    - platform: state
      entity_id:
        - device_tracker.mfc_ios
        - device_tracker.mfc_iphone_nmap
        - device_tracker.mfc_iphone_owntrack_mfc
        - device_tracker.e3c67d6b51bf445ba241a0045bfe0222 #MFC
      to: 'home'
  condition:
    condition: state
    entity_id: input_boolean.home_mfc
    state: 'off'
  action:
    service: homeassistant.turn_on
    entity_id: input_boolean.home_mfc
#
# PALOMA: Control Presencia => input_boolean.home_paf
#
- id: update_tracker_to_not_home_paf
  alias: 'Home 2 Away PAF'
  initial_state: True
  trigger:
    - platform: state
      entity_id: device_tracker.93e3d52336a54d4d898b204abdf3ee94 #PAF
      to: 'not_home'
  condition:
    condition: state
    entity_id: input_boolean.home_paf
    state: 'on'
  action:
    service: homeassistant.turn_off
    entity_id: input_boolean.home_paf

- id: update_nmap_to_not_home_paf
  alias: 'Home 2 Away PAF NMAP'
  initial_state: True
  trigger:
    - platform: state
      entity_id: device_tracker.paf_iphone_nmap
      to: 'not_home'
      for: '00:10:00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.home_paf
        state: 'on'
      - condition: time
        after: '08:00:00'
      - condition: time
        before: '23:59:00'
  action:
    service: homeassistant.turn_off
    entity_id: input_boolean.home_paf

- id: update_tracker_to_home_paf
  alias: 'Away to Home PAF'
  initial_state: True
  trigger:
    - platform: state
      entity_id:
        - device_tracker.paf_iphone_nmap
        - device_tracker.93e3d52336a54d4d898b204abdf3ee94 #PAF
      to: 'home'
  condition:
    condition: state
    entity_id: input_boolean.home_paf
    state: 'off'
  action:
    service: homeassistant.turn_on
    entity_id: input_boolean.home_paf
#
# AGU: Control Presencia => input_boolean.agu
#
- id: update_tracker_to_not_home_aaf
  alias: 'Home 2 Away AAF'
  initial_state: True
  trigger:
    - platform: state
      entity_id: device_tracker.bef743fa74f2464ba458612ad3e1c195
      to: 'not_home'
  condition:
    condition: state
    entity_id: input_boolean.home_aaf
    state: 'on'
  action:
    service: homeassistant.turn_off
    entity_id: input_boolean.home_aaf

- id: update_nmap_to_not_home_aaf
  alias: 'Home 2 Away AAF NMAP'
  initial_state: True
  trigger:
    - platform: state
      entity_id: device_tracker.aaf_iphone_nmap
      to: 'not_home'
      for: '00:10:00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.home_aaf
        state: 'on'
      - condition: time
        after: '08:00:00'
      - condition: time
        before: '23:59:00'
  action:
    service: homeassistant.turn_off
    entity_id: input_boolean.home_aaf

- id: update_tracker_to_home_aaf
  alias: 'Away to Home AAF'
  initial_state: True
  trigger:
    - platform: state
      entity_id:
        - device_tracker.aaf_iphone_nmap
        - device_tracker.bef743fa74f2464ba458612ad3e1c195
      to: 'home'
  condition:
    condition: state
    entity_id: input_boolean.home_aaf
    state: 'off'
  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.home_aaf

#
# FAMILY AT HOME: Reglas de Home / Away
#
- id: family_home_to_away
  alias: 'Family Home to Away'
  trigger:
    platform: state
    entity_id: group.family_home_grp
    from: 'on'
    to: 'off'
  action:
    - service: script.turn_on
      entity_id: script.mensaje_family
      data:
        variables:
          title: 'FAMILY at HOME?'
          message: '==> Nadie en Casa'
    - service: light.turn_off
      entity_id:
        - group.luces_entrada_grp
        - group.luces_salon_grp
        - group.luces_estudio_grp
    - service: script.turn_on
      entity_id: script.mensaje_family
      data:
        variables:
          title: ' '
          message: '==> Luces OFF'

- id: family_home_to_away
  alias: 'Family Home at Home'
  trigger:
    - platform: state
      entity_id: group.family_home_grp
      from: 'off'
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: sun
        after: sunset
      - condition: time
        before: '23:59:00'
  action:
    - service: script.turn_on
      entity_id: script.mensaje_family
      data:
        variables:
          title: 'FAMILY at HOME?'
          message: '==> Hay alguien en Casa'
    - service: light.turn_on
      entity_id: light.hue_cocina
    - service: script.turn_on
      entity_id: script.mensaje_family
      data:
        variables:
          title: ' '
          message: '==> Luces Piloto ON'

#
# ALARMA: Armado y Control de la Alarma
#
- id: alarm_test_notification
  alias: 'Alarm Test Notification'
  trigger:
    platform: state
    entity_id: input_boolean.home_armed
    from: 'off'
    to: 'on'
  action:
    - service: script.turn_on
      entity_id: script.mensaje_family
      data:
        variables:
          title: 'ALARMA'
          message: '==> TEST Mensaje Alarma'
    #- service: script.turn_on
    #  entity_id: script.telegram_alarm_send_photo
