homeassistant:
  # Name of the location where Home Assistant is running
  name: Álvarez Fijo Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 172
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Madrid
  # Customization file
  customize: !include customize.yaml

group: !include groups.yaml
script: !include scripts.yaml
automation: !include automations.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  api_password: !secret http_password
  ssl_certificate: /etc/letsencrypt/live/alvarea.duckdns.org/fullchain.pem
  ssl_key: /etc/letsencrypt/live/alvarea.duckdns.org/privkey.pem
  base_url: !secret http_base_url

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# AAC. Sensores de Tiempo, sol, Luna,
sensor:
  - platform: yweather
    woeid: 90231690
    name: Hoy
    monitored_conditions:
      - weather
      - temperature
      - temp_min
      - temp_max
      - wind_speed
      - humidity
  - platform: yweather
    woeid: 90231690
    forecast: 1
    name: Mañana
    monitored_conditions:
      - weather
      - temperature
      - temp_min
      - temp_max
      - wind_speed
      - humidity
  - platform: time_date
    display_options:
      - 'time'
  - platform: uptime
    unit_of_measurement: hours
  - platform: moon
  - platform: cert_expiry
    host: alvarea.duckdns.org
    port: 443
  - platform: systemmonitor
    resources:
      - type: load_15m
      - type: processor_use
      - type: memory_use_percent
      - type: memory_use
      - type: memory_free
      - type: disk_use_percent
        arg: /
      - type: disk_use
        arg: /
      - type: disk_free
        arg: /
      - type: swap_use_percent
      - type: last_boot

# Text to speech
#tts:
#  - platform: google

# Cloud
#cloud:

# AAC. Philips Hue Bridge
hue:
  bridges:
    - host: 192.168.0.17

# AAC. Dispositivos Apple IOS
ios:

# AAC. GENERIC IP CAMERA
camera:
  - platform: generic
    still_image_url: https://api.sat24.com/mostrecent/SP/visual5hdcomplete%20width=500%20height=304
    name: Weather Satelite
  - platform: generic
    still_image_url: http://192.168.0.12:8080/snapshot.cgi
    name: IPcam12 Estudio
    username: admin
    password: !secret IPcam12
  - platform: generic
    still_image_url: http://192.168.0.11/snapshot/image0.jpg
    name: IPcam11 Cocina
    username: admin
    password: !secret IPcam11

apple_tv:
  - host: 192.168.0.19
    login_id: 00000000-5540-7268-ea1c-2a4e4d154343
    name: Apple TV
    credentials: 906CB00CF5F3A299:84CB3B3A11823C334BD48BAB463C0B625392E4BEF4F2817F19361BE285C0BEB1

# AAC. MQTT - BROKER: CLOUDMQTT
mqtt:
  broker: m23.cloudmqtt.com
  port: 11024
  client_id: hass_alvarea
  keepalive: 60
  username: HASS
  password: !secret cloudmqtt

# AAC. NMAP, OWNTRACKS
device_tracker:
  - platform: nmap_tracker
    hosts:
      - 192.168.0.10
      - 192.168.0.50-99
    home_interval: 10
    exclude:
     - 192.168.0.23
  - platform: owntracks
    mqtt_topic: "owntracks/#"
  - platform: geofency

# AAC. Interruptores control presencia Family
input_boolean:
  mfchome:
    name: MFC Home
    initial: off
    icon: mdi:cellphone-iphone
  aachome:
    name: AAC Home
    initial: off
    icon: mdi:cellphone-iphone
  pafhome:
    name: PAF Home
    initial: off
    icon: mdi:cellphone-iphone
  aafhome:
    name: AAF Home
    initial: off
    icon: mdi:cellphone-iphone
  luceshome:
    name: Luces Interior
    initial: off
    icon: mdi:lightbulb-on

# AAC. Mediaplayer FireTV
media_player:
  - platform: firetv
    name: FireTV Cocina

#
# TEMAS PENDIENTES
#

# AAC. PROSEGUR
#alarm_control_panel:
#  - platform: totalconnect
#    username: agustin.alvarezconesa@gmail.com
#    password: Casuario2018

# AAC. TV Sony
# media_player:
#   - platform: braviatv
#     host: 192.168.0.14
#     name: TV Sony Salón
#   - platform: braviatv
#     host: 192.168.0.15
#     name: TV Sony Estudio
