homeassistant:
  # Name of the location where Home Assistant is running
  name: HOMY home assistant
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 172
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Madrid
  # Customization file
  customize: !include customize.yaml

group: !include groups.yaml
script: !include scripts.yaml
automation: !include automations.yaml

sensor: !include sensor.yaml
binary_sensor: !include binary_sensor.yaml
input_boolean: !include input_boolean.yaml
input_select: !include input_select.yaml
input_text: !include input_text.yaml
input_number: !include input_number.yaml
input_datetime: !include input_datetime.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Enable Python Scripts
python_script:

http:
  api_password: !secret http_api_password
  ssl_certificate: /home/homeassistant/dehydrated/certs/alvarea.duckdns.org/fullchain.pem
  ssl_key: /home/homeassistant/dehydrated/certs/alvarea.duckdns.org/privkey.pem
  base_url: !secret http_base_url
  trusted_networks:
    - 192.168.0.1
  ip_ban_enabled: True
  login_attempts_threshold: 10

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Philips Hue Bridge
hue:
  bridges:
    - host: 192.168.0.17

# Dispositivos Apple IOS
ios:

# Text to speech
#tts:
#  - platform: google

# Cloud
#cloud:

# ALARM MANUAL CONTROL PANEL
#
#   TRANSICION: Disarmed => Armed (Home/Night/Away) => Triggered => Disarmed
#
#   STATUS      DURACION TRANSICION               DESCRIPCION
#   ========    =============================     ==================================================
#   DISARMED    Permanante                        Estado inicial de alarma desarmada
#
#   PENDING     <PENDING_TIME>                    Estado transición a ARMED durante <pending_time> Segundos
#
#   ARMED_AWAY  Permanante                        Estado de alarma ARMED HOME / ARMED AWAY
#
#   PENDING     <PENDING_TIME> + <DELAY_TIME>     Estado transición a TRIGGERED durante <pending_time> + <delay_time> Segundos
#
#   TRIGGERED   <TRIGGER_TIME>                    Estado de alarma TRIGGERED durante <trigger_time> segundos
#
#   ARMED_AWAY  Permanante                        Estado anterior de alarma armada
#
alarm_control_panel:
  - platform: manual
    name: HA
    # code: !secret alarm_control_code
    # Pending: The time in seconds of the pending time before effecting a state change. Default is 60 seconds.
    # Delay: The time in seconds of the pending time before triggering the alarm. Default is 0 seconds.
    # Trigger: The time in seconds of the trigger time in which the alarm is firing. Default is 120 seconds
    pending_time: 15
    delay_time: 15
    trigger_time: 120
    disarmed:
      trigger_time: 0 # the disarmed state never triggers the alarm;
    armed_home:
      pending_time: 0
      delay_time: 0

# Timer temporizador Depuradora Piscina
timer:
  piscina:
    name: Tiempo Restante (Timer)
    icon: mdi:timer

counter:
  nespresso_start:
    initial: 0
    step: 1

history_graph:
  piscina_duracion:
    entities:
      - sensor.piscina_duracion_programa
    name: Duracion Depuradora Piscina
    hours_to_show: 168
    refresh: 1800


# GENERIC IP CAMERA
camera:
  - platform: generic
    still_image_url: https://api.sat24.com/mostrecent/SP/visual5hdcomplete%20width=500%20height=304
    name: Weather Satelite
  - platform: generic
    still_image_url: http://192.168.0.12:8080/snapshot.cgi
    name: IPcam12 Estudio
    username: admin
    password: !secret IPcam12
  - platform: generic
    still_image_url: http://192.168.0.11/snapshot/image0.jpg
    name: IPcam11 Cocina
    username: admin
    password: !secret IPcam11

apple_tv:
  - host: 192.168.0.19
    login_id: 00000000-5540-7268-ea1c-2a4e4d154343
    name: Apple TV
    credentials: 906CB00CF5F3A299:84CB3B3A11823C334BD48BAB463C0B625392E4BEF4F2817F19361BE285C0BEB1

# Mediaplayer FireTV
#media_player:
#  - platform: firetv
#    name: FireTV Cocina

# MQTT - BROKER: CLOUDMQTT
mqtt:
  broker: alvarea.duckdns.org
  port: 1883
  client_id: hassbian_alvarea
  keepalive: 60
  username: hassbian_mqtt
  password: !secret hassbian_mqtt
  discovery: true
  discovery_prefix: homeassistant

#  broker: m23.cloudmqtt.com
#  port: 11024
#  client_id: hass_alvarea
#  keepalive: 60
#  username: HASS
#  password: !secret cloudmqtt

# XIAOMI AQARA GATEWAY
#
xiaomi_aqara:
  gateways:
    - mac: !secret xiaomi_gateway
      key: AD58F3C5D30D405C

# NMAP, OWNTRACKS
device_tracker:
  - platform: geofency
  #- platform: owntracks
  #  mqtt_topic: "owntracks/#"
  - platform: nmap_tracker
    hosts:
      - 192.168.0.50-70
    home_interval: 10
    consider_home: 0:10:00
    interval_seconds: 20
    #exclude:
    #- 192.168.0.23

# NOTIFICACIONES
notify:
  - platform: group # notification group for IOS
    name: notifica_grupo_ios
    services:
      - service: ios_aac_ios
      - service: ios_mfc_ios
      - service: ios_paf_ios
      - service: ios_aaf_ios

  - name: telegram_alarm
    platform: telegram
    chat_id: !secret telegram_grp_alarm
  - name: telegram_notify
    platform: telegram
    chat_id: !secret telegram_grp_notif
  - name: telegram_aac
    platform: telegram
    chat_id: !secret telegram_chat_aac
  #- name: telegram_mfc
  #  platform: telegram
  #  chat_id: !secret telegram_chat_mfc
  #- name: telegram_paf
  #  platform: telegram
  #  chat_id: !secret telegram_chat_paf
  #- name: telegram_aaf
  #  platform: telegram
  #  chat_id: !secret telegram_chat_aaf

# Notifications via Telegram Bot
telegram_bot:
  - platform: polling
    api_key: !secret telegram_apikey
    allowed_chat_ids:
      - !secret telegram_grp_notif
      - !secret telegram_grp_alarm
      #- !secret telegram_chat_aac

# Enables a map showing the location of tracked devices
map:

zone:
  - name: Heineken
    latitude: 37.3876837
    longitude: -5.9645631
    icon: mdi:beer
    radius: 50
  - name: Faeca
    latitude: 37.393004
    longitude: -5.957486
    icon: mdi:tree
    radius: 50
  - name: Casa Abuela
    latitude: 37.3748
    longitude: -6.0530
    icon: mdi:home-account


#
# Restaurar valores tras reinicio
#
#recorder:
#  include:
#    domains:
#      - binary_sensor
#      - sensor
#      - input_boolean
#      - input_text
#      - input_select
#      - switch
#      - media_player

# TV Sony
# media_player:
#   - platform: braviatv
#     host: 192.168.0.14
#     name: TV Sony Salón
#   - platform: braviatv
#     host: 192.168.0.15
#     name: TV Sony Estudio
