homeassistant:
  # Name of the location where Home Assistant is running
  name: HOMY home assistant
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 172
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Madrid
  # Customization file
  customize: !include customize.yaml
#  auth_providers:
#    - type: homeassistant
#    - type: trusted_networks
#      trusted_networks:
#        - 127.0.0.1
#        - 192.168.0.0/24

# External configuration files
group: !include groups.yaml
script: !include scripts.yaml
automation: !include automations.yaml
sensor: !include sensor.yaml
binary_sensor: !include binary_sensor.yaml
input_boolean: !include input_boolean.yaml
input_select: !include input_select.yaml
input_text: !include input_text.yaml
input_number: !include input_number.yaml
input_datetime: !include input_datetime.yaml
zone: !include zone.yaml

# This integration is a meta-component and configures a default set of integrations for Home Assistant to load.
default_config:

# The integrations that will be loaded are:
#   automation
#   cloud
#   config
#   frontend
#   history
#   logbook
#   map
#   mobile_app
#   person
#   script
#   ssdp
#   sun
#   system_health
#   updater
#   zeroconf

# Enables the frontend
#frontend:

# Enables configuration UI
#config:

# Enables support for tracking state changes over time
#history:

# View all events in a logbook
#logbook:

# Track the sun
#sun:

# Enable System Health View
#system_health:

# Enables a map showing the location of tracked devices
#map:

#shopping_list:

# Enable Python Scripts
python_script:

http:
  server_port: 2309
  ip_ban_enabled: true
  login_attempts_threshold: 5
  base_url: https://alvareahomy.duckdns.org
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:
  ignore:
    - igd
    - xiaomi_gw
    - esphome


# Philips Hue Bridge
hue:
  bridges:
    - host: 192.168.0.20
      allow_unreachable: true

# Dispositivos Apple IOS
ios:

# ALARM MANUAL CONTROL PANEL
#
#   TRANSICION: Disarmed => Armed (Home/Night/Away) => Triggered => Disarmed
#
#   STATUS      DURACION TRANSICION               DESCRIPCION
#   ========    =============================     ==================================================
#   DISARMED    Permanante                        Estado inicial de alarma desarmada
#   PENDING     <PENDING_TIME>                    Estado transición a ARMED durante <pending_time> Segundos
#   ARMED_AWAY  Permanante                        Estado de alarma ARMED HOME / ARMED AWAY
#   PENDING     <PENDING_TIME> + <DELAY_TIME>     Estado transición a TRIGGERED durante <pending_time> + <delay_time> Segundos
#   TRIGGERED   <TRIGGER_TIME>                    Estado de alarma TRIGGERED durante <trigger_time> segundos
#   ARMED_AWAY  Permanante                        Estado anterior de alarma armada
#
alarm_control_panel:
  - platform: manual
    name: HA
    # code: !secret alarm_control_code
    # Pending: The time in seconds of the pending time before effecting a state change. Default is 60 seconds.
    # Delay: The time in seconds of the pending time before triggering the alarm. Default is 0 seconds.
    # Trigger: The time in seconds of the trigger time in which the alarm is firing. Default is 120 seconds
    pending_time: 15
    delay_time: 30
    trigger_time: 300
    disarmed:
      trigger_time: 0 # the disarmed state never triggers the alarm;
    armed_home:
      pending_time: 0
      delay_time: 0

# Timer temporizadores
timer:
  piscina:
    name: Timer Piscina
    icon: mdi:timer
  riego_ch1:
    name: Timer CH1
    icon: mdi:timer
  riego_ch2:
    name: Timer CH2
    icon: mdi:timer
  riego_ch3:
    name: Timer CH3
    icon: mdi:timer
  riego_ch4:
    name: Timer CH4
    icon: mdi:timer
  fzen_sw2:
    name: Timer Fuente Frog
    icon: mdi:timer

#counter:
#  nespresso_start:
#    initial: 0
#    step: 1

#history_graph:
#  piscina_duracion:
#    entities:
#      - binary_sensor.piscina_status
#    name: Duracion Depuradora Piscina
#    hours_to_show: 168
#    refresh: 1800

# GENERIC IP CAMERA
camera:
  - platform: generic
    still_image_url: https://api.sat24.com/mostrecent/SP/visual5hdcomplete%20width=500%20height=304
    name: Weather Satelite
  - platform: generic
    still_image_url: !secret still_image_url_cam_estudio
    name: IPcam Estudio
    username: admin
    password: !secret IPcam_estudio
  - platform: generic
    still_image_url: !secret still_image_url_cam_jardin
    stream_source: !secret stream_source_url_cam_jardin
    name: IPcam Jardín
    username: admin
    password: !secret IPcam_jardin

#ffmpeg:

#apple_tv:
#  - host: !secret apple_tv_host
#    login_id: !secret apple_tv_loginid
#    name: Apple TV
#    credentials: !secret apple_tv_credentials

# Mediaplayer FireTV
media_player:
  - platform: androidtv
    name: Fire TV
    host: !secret firetv_host
    adbkey: "/config/android/adbkey"
    #    adbkey: "/home/homeassistant/.homeassistant/config/android/adbkey"

# MQTT - BROKER: Local Mosquitto Broker
#
#mqtt:
#  broker: alvarea.duckdns.org
#  port: 1883
#  client_id: hassbian_alvarea
#  keepalive: 60
#  username: hassbian_mqtt
#  password: !secret hassbian_mqtt
#  discovery: true
#  discovery_prefix: homeassistant#

#  broker: m23.cloudmqtt.com
#  port: 11024
#  client_id: hass_alvarea
#  keepalive: 60
#  username: HASS
#  password: !secret cloudmqtt

# XIAOMI AQARA GATEWAY
xiaomi_aqara:
  discovery_retry: 10
  gateways:
    - mac: !secret xiaomi_mac
      key: !secret xiaomi_gateway

# NMAP
device_tracker:
  - platform: nmap_tracker
    hosts: !secret device_tracker_range1
    home_interval: 10
    consider_home: 0:10:00
    interval_seconds: 60
    track_new_devices: yes
    scan_options: -Pn --host-timeout 5s
    exclude:
      - !secret device_tracker_host1
  - platform: ping
    hosts:
      ping_57_amazon_kindle: 192.168.0.57

# GEOFENCY: Platform & Device Tracker ==> changed on v.0.83.2
geofency:

# OWNTRACKS: Device tracker integration using Nabu Cloud
#owntracks:
  #max_gps_accuracy: 300
  #waypoints: false
  #mqtt_topic: "owntracks/#"
  #events_only: true

# NOTIFICACIONES
notify:
  - platform: group # notification group for IOS
    name: notifica_grupo_ios
    services:
      - service: mobile_app_iphone_aac
      - service: mobile_app_iphone_malen
      - service: mobile_app_iphone_paf
      - service: ios_aaf_ios
  - name: telegram_alarm
    platform: telegram
    chat_id: !secret telegram_grp_alarm
  - name: telegram_notify
    platform: telegram
    chat_id: !secret telegram_grp_notif
  - name: telegram_aac
    platform: telegram
    chat_id: !secret telegram_aac

  #- name: pushover_aac
  #  platform: pushover
  #  api_key: uovpmpj3cv6ijvyo6dcma2eaeaa8ts
  #  user_key: aac_ios
  #- name: telegram_mfc
  #  platform: telegram
  #  chat_id: !secret telegram_chat_mfc
  #- name: telegram_paf
  #  platform: telegram
  #  chat_id: !secret telegram_chat_paf
  #- name: telegram_aaf
  #  platform: telegram
  #  chat_id: !secret telegram_chat_aaf

# Notifications via Telegram Bot
telegram_bot:
  - platform: polling
    api_key: !secret telegram_apikey
    allowed_chat_ids:
      - !secret telegram_grp_notif
      - !secret telegram_grp_alarm
      #- !secret telegram_chat_aac

alert:
  alerta_alarma_ha:
    name: ALERTA - ALARMA HOMY ACTIVADA
    done_message: Alarma Desactivada OK
    entity_id: alarm_control_panel.ha
    state: 'triggered'
    repeat: 1
    can_acknowledge: true
    skip_first: true
    notifiers:
      - telegram_alarm

  alerta_test:
    name: ALERTA - LUCES ENCENDIDAS DE DIA
    done_message: Test Alerta De Día Solucionado
    entity_id: binary_sensor.test_alert_sensor
    state: 'on'
    repeat: 1
    can_acknowledge: true
    skip_first: false
    notifiers:
      - telegram_aac

light:
  - platform: group
    name: Luces Planta Baja
    entities:
      - light.cocina
      - light.dormitorio
      - light.entrada
      - light.pasillo
      - light.salon
  - platform: group
    name: Luces Planta Alta
    entities:
      - light.luces_estudio
  - platform: group
    name: Luces Estudio
    entities:
      - light.estudio
      - light.esphome_lb1_l01
  - platform: group
    name: Luces Interior
    entities:
      - light.luces_planta_baja
      - light.luces_planta_alta

# Cloud -  Home Assistant Cloud - NABU CASA
cloud:
 alexa:
    filter:
      include_domains:
        - switch
      exclude_domains:
        - alert
        - automation
        - input_boolean
        - sensor
        - light
        - group
        - script
      include_entities:
        - light.luces_planta_baja
        - light.luces_planta_alta
        - light.luces_interior
        - light.luces_salon
        - light.esphome_lb1_l01
        - group.luces_exterior_grp
        - group.luces_casa_grp
        - script.homy_armado_parcial
        - script.homy_armado_total
        - script.homy_desarmado_code
      exclude_entities:
        - switch.esphome_bas_sw0
        - switch.esphome_bas_sw1
        - switch.esphome_bas_sw2
        - switch.esphome_bas_sw3
        - switch.esphome_bas_sw4
        - switch.esphome_pow_sw
        - switch.esphome_pow_sw2
        - light.luz_cilindro
        - light.luz_cocina
        - light.luz_entrada
        - light.luz_estudio
        - light.luz_lectura
        - light.luz_pasillo
        - light.luz_vitrina
        - light.entrada
        - light.cocina
        - light.estudio
        - light.pasillo
        - light.salon
        - light.esphome_4ch_blue_led
        - light.esphome_bas_sw1_led
        - light.esphome_bas_sw2_led
        - light.esphome_bas_sw4_led
        - light.esphome_pow_sw3_led
        - light.esphome_pow_sw1_led
        - light.esphome_s20_nespresso_led
        - light.esphome_s20_sw1_led
        - light.esphome_s20_sw2_led
        - light.esphome_s20_sw3_led
    entity_config:
      script.homy_armado_parcial:
        name: Armado Parcial
      script.homy_armado_total:
        name: Armado Total
      script.homy_desarmado_code:
        name: !secret desarmado_code
      group.luces_toda_la_casa_grp:
        name: Luces Toda La Casa
        description: Luces Interior y Exterior
      group.luces_exterior_grp:
        name: Luces Exterior y Jardín
      switch.wall_switch_left_158d0002236e75:
        display_categories: LIGHT
      switch.wall_switch_right_158d0002236e75:
        display_categories: LIGHT
      switch.esphome_4ch_relay_1:
        display_categories: LIGHT
      switch.esphome_4ch_relay_2:
        display_categories: LIGHT
      switch.esphome_4ch_relay_3:
        display_categories: LIGHT
      switch.esphome_4ch_relay_4:
        display_categories: LIGHT
      switch.esphome_bas_sw1:
        display_categories: LIGHT
      switch.esphome_bas_sw4:
        display_categories: LIGHT
      light.esphome_lb1_l01:
        display_categories: LIGHT

recorder:
  purge_interval: 1
  purge_keep_days: 30
  exclude:
    domains:
      - input_boolean
      - input_text
      - input_select
      - media_player
      - camera
      - automation
      - climate
      - group
      - script
      - sun
      - weather
      - zone

weather:
  - platform: darksky
    api_key: !secret weather_apikey
    mode: daily

apcupsd:
  host: 127.0.0.1
  port: 3551

person:

# The stream component provides a way to proxy live streams through Home Assistant.
# The component currently only supports the HLS format.
stream:


blink:
  username: !secret blink_usr
  password: !secret blink_pwd
  scan_interval: 600
  binary_sensors:
    monitored_conditions:
      - motion_enabled
      - motion_detected
  sensors:
    monitored_conditions:
      - battery

#
# Sensores Xiaomi Miflora - C
#
#plant:


#
# Sensores Xiaomi Miflora - Componente Plant - Basado en ESP32S
#
plant:
  miflora_s1:
    sensors:
      moisture: sensor.xiaomi_miflora_humedad
      battery: sensor.xiaomi_miflora_bateria
      temperature: sensor.xiaomi_miflora_temperatura
      conductivity: sensor.xiaomi_miflora_fertilidad
      brightness: sensor.xiaomi_miflora_luminosidad
    min_moisture: 1
    max_moisture: 50
    min_conductivity: 350
    max_conductivity: 2000
    min_temperature: 10
    max_temperature: 32
    min_brightness: 1000
    max_brightness: 50000
    min_battery: 20
#
#  Sensores Miflorea - Basado en Sensor Bluetooth Nativo Rasperry y Componente mitemp_by
#  miflora_s1:
#    sensors:
#      moisture: sensor.mi_m_c47c8d67c19e
#      battery: sensor.mi_b_c47c8d67c19e
#      temperature: sensor.mi_t_c47c8d67c19e
#      conductivity: sensor.mi_c_c47c8d67c19e
#      brightness: sensor.mi_l_c47c8d67c19e
#    min_moisture: 20
#    max_moisture: 60
#    min_conductivity: 350
#    max_conductivity: 2000
#    min_temperature: 10
#    max_temperature: 32
#    min_brightness: 1000
#    max_brightness: 30000
#    min_battery: 20

# sensor.
#    platform: mitemp_bt
#      batt_entities: True

# TV Sony
# media_player:
#   - platform: braviatv
#     host: 192.168.0.14
#     name: TV Sony Salón
#   - platform: braviatv
#     host: 192.168.0.15
#     name: TV Sony Estudio


#TO DO
#
# https://github.com/custom-components/custom_updater/wiki/Installation
# custom_updater:
#  card_urls:
#    - https://raw.githubusercontent.com/kalkih/mini-graph-card/master/tracker.json
