homeassistant:
  # Name of the location where Home Assistant is running
  name: Álvarez Fijo Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 172
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Madrid
  # Customization file
  customize: !include customize.yaml

group: !include groups.yaml
script: !include scripts.yaml
automation: !include automations.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

# AAC. Enable Python Scripts
python_script:

http:
  api_password: !secret http_api_password
  ssl_certificate: /etc/letsencrypt/live/alvarea.duckdns.org/fullchain.pem
  ssl_key: /etc/letsencrypt/live/alvarea.duckdns.org/privkey.pem
  base_url: !secret http_base_url
  trusted_networks:
    - 192.168.0.1
  ip_ban_enabled: True
  login_attempts_threshold: 10

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

zone:
  - name: Heineken
    latitude: 37.3876837
    longitude: -5.9645631
    icon: mdi:beer
    radius: 50
  - name: Faeca
    latitude: 37.393004
    longitude: -5.957486
    icon: mdi:tree
    radius: 50
  - name: Casa Abuela
    latitude: 37.3748
    longitude: -6.0530
    icon: mdi:home-account

# Track the sun
sun:

# Text to speech
#tts:
#  - platform: google

# Cloud
#cloud:

# AAC. Philips Hue Bridge
hue:
  bridges:
    - host: 192.168.0.17

# AAC. Dispositivos Apple IOS
ios:

notify:
  - platform: group # notification group for IOS
    name: ios
    services:
      - service: ios_aac_ios
  - platform: telegram
    name: telegram_family
    chat_id: !secret telegram_chat_fam
  - platform: telegram
    name: telegram_aac
    chat_id: !secret telegram_chat_aac
  - platform: telegram
    name: telegram_mfc
    chat_id: !secret telegram_chat_mfc

# AAC. Notifications via Telegram Bot
telegram_bot:
  - platform: polling
    api_key: !secret telegram_apikey
    allowed_chat_ids:
      - !secret telegram_chat_aac
      - !secret telegram_chat_mfc
      - !secret telegram_chat_fam

# AAC. GENERIC IP CAMERA
camera:
  - platform: generic
    still_image_url: https://api.sat24.com/mostrecent/SP/visual5hdcomplete%20width=500%20height=304
    name: Weather Satelite
  - platform: generic
    still_image_url: http://192.168.0.12:8080/snapshot.cgi
    name: IPcam12 Estudio
    username: admin
    password: !secret IPcam12
  - platform: generic
    still_image_url: http://192.168.0.11/snapshot/image0.jpg
    name: IPcam11 Cocina
    username: admin
    password: !secret IPcam11

apple_tv:
  - host: 192.168.0.19
    login_id: 00000000-5540-7268-ea1c-2a4e4d154343
    name: Apple TV
    credentials: 906CB00CF5F3A299:84CB3B3A11823C334BD48BAB463C0B625392E4BEF4F2817F19361BE285C0BEB1

# AAC. MQTT - BROKER: CLOUDMQTT
mqtt:
  broker: m23.cloudmqtt.com
  port: 11024
  client_id: hass_alvarea
  keepalive: 60
  username: HASS
  password: !secret cloudmqtt

# AAC. NMAP, OWNTRACKS
device_tracker:
  - platform: geofency
  - platform: owntracks
    mqtt_topic: "owntracks/#"
  - platform: nmap_tracker
    hosts:
      - 192.168.0.10
      - 192.168.0.50-99
    home_interval: 10
    consider_home: 0:10:00
    exclude:
     - 192.168.0.23

# AAC. Interruptores control presencia Family
input_boolean:
  home_mfc:
    name: Malen
    initial: on
    icon: mdi:cellphone-iphone
  home_aac:
    name: Agustin
    initial: on
    icon: mdi:cellphone-iphone
  home_paf:
    name: Paloma
    initial: on
    icon: mdi:cellphone-iphone
  home_aaf:
    name: Agu
    initial: on
    icon: mdi:cellphone-iphone
  notify_mfc:
    name: Notificaciones Malen
    initial: on
    icon: mdi:bell-ring
  notify_aac:
    name: Notificaciones Agustin
    initial: on
    icon: mdi:bell-ring
  notify_paf:
    name: Notificaciones Paloma
    initial: off
    icon: mdi:bell-ring
  notify_aaf:
    name: Notificaciones Agu
    initial: off
    icon: mdi:bell-ring
# AAC. Interruptores control alarma y notificaciones
  alarm_mode:
    name: Alarma Botón Pánico
    initial: off
    icon: mdi:security-home

# AAC. Modo Notificaciones
input_select:
  home_notify:
    name: Notificaciones
    options:
     - 'Off'
     - 'Telegram'
     - 'IOS'
    initial: Telegram
    icon: mdi:bell-ring
  home_last_change:
    name: Last Home Tracking
    options:
     - 'Agustín'
     - 'Malen'
     - 'Agu'
     - 'Paloma'
    initial: 'Agustín'
    icon: mdi:home-account

# AAC. Mensaje para Notificaciones
input_text:
  mensaje_tit:
    name: Titulo Notificaciones
    initial: <OK>
  mensaje_msg:
    name: Cuerpo Notificaciones
    initial: <OK>


# AAC. Mediaplayer FireTV
media_player:
  - platform: firetv
    name: FireTV Cocina

sensor:
#
# AAC. Sensores del Sistema
#
  - platform: time_date
    display_options:
      - 'time'
  - platform: uptime
    unit_of_measurement: hours
  - platform: moon
  - platform: cert_expiry
    host: alvarea.duckdns.org
    port: 443
  - platform: systemmonitor
    resources:
      - type: load_15m
      - type: processor_use
      - type: memory_use_percent
      - type: memory_use
      - type: memory_free
      - type: disk_use_percent
        arg: /
      - type: disk_use
        arg: /
      - type: disk_free
        arg: /
      - type: swap_use_percent
      - type: last_boot
#
# AAC. Sensores de Previsiones de Tiempo
#
  - platform: yweather
    woeid: 90231690
    name: Hoy
    monitored_conditions:
      - weather
      - temperature
      - temp_min
      - temp_max
      - wind_speed
      - humidity
  - platform: yweather
    woeid: 90231690
    forecast: 1
    name: Mañana
    monitored_conditions:
      - weather
      - temperature
      - temp_min
      - temp_max
      - wind_speed
      - humidity

# AAC. Platform Template
#
  - platform: template
    sensors:
      sun_next_setting:
        value_template: '{{ as_timestamp(states.sun.sun.attributes.next_setting)  | timestamp_custom("%H:%M") }}'
        friendly_name: 'Próxima Puesta de Sol'
        icon_template: mdi:weather-sunset-down
      sun_next_rising:
        value_template: '{{ as_timestamp(states.sun.sun.attributes.next_rising)  | timestamp_custom("%H:%M") }}'
        friendly_name: 'Próxima Salida de Sol'
        icon_template: mdi:weather-sunset-up
      bateria_presencia_entrada:
        # binary_sensor.motion_sensor_158d0001e55903
        value_template: "{{ states.binary_sensor.motion_sensor_158d0001e55903.attributes.battery_level|default(-1)|int if states.binary_sensor.motion_sensor_158d0001e55903 is not none }}"
        friendly_name: 'Batería Sensor Presencia Entrada'
        unit_of_measurement: '%'
        icon_template: '{% if states.binary_sensor.motion_sensor_158d0001e55903.attributes.battery_level == 100 %}
                           mdi:battery
                        {% elif states.binary_sensor.motion_sensor_158d0001e55903.attributes.battery_level >= 90 %}
                           mdi:battery-90
                        {% elif states.binary_sensor.motion_sensor_158d0001e55903.attributes.battery_level >= 80 %}
                           mdi:battery-80
                        {% elif states.binary_sensor.motion_sensor_158d0001e55903.attributes.battery_level >= 70 %}
                           mdi:battery-70
                        {% elif states.binary_sensor.motion_sensor_158d0001e55903.attributes.battery_level >= 60 %}
                           mdi:battery-60
                        {% elif states.binary_sensor.motion_sensor_158d0001e55903.attributes.battery_level >= 50 %}
                           mdi:battery-50
                        {% elif states.binary_sensor.motion_sensor_158d0001e55903.attributes.battery_level >= 40 %}
                           mdi:battery-40
                        {% elif states.binary_sensor.motion_sensor_158d0001e55903.attributes.battery_level >= 30 %}
                           mdi:battery-30
                        {% elif states.binary_sensor.motion_sensor_158d0001e55903.attributes.battery_level >= 20 %}
                           mdi:battery-20
                        {% elif states.binary_sensor.motion_sensor_158d0001e55903.attributes.battery_level >= 10 %}
                           mdi:battery-10
                        {% else %}
                           battery-outline
                        {% endif %}'
      bateria_puerta_entrada:
        # binary_sensor.door_window_sensor_158d00022b393c
        friendly_name: 'Batería Sensor Puerta Entrada'
        value_template: "{{ states.binary_sensor.door_window_sensor_158d00022b393c.attributes.battery_level|default(-1)|int if states.binary_sensor.door_window_sensor_158d00022b393c is not none }}"
        unit_of_measurement: '%'
        icon_template: '{% if states.binary_sensor.door_window_sensor_158d00022b393c.attributes.battery_level == 100 %}
                           mdi:battery
                        {% elif states.binary_sensor.door_window_sensor_158d00022b393c.attributes.battery_level >= 90 %}
                           mdi:battery-90
                        {% elif states.binary_sensor.door_window_sensor_158d00022b393c.attributes.battery_level >= 80 %}
                           mdi:battery-80
                        {% elif states.binary_sensor.door_window_sensor_158d00022b393c.attributes.battery_level >= 70 %}
                           mdi:battery-70
                        {% elif states.binary_sensor.door_window_sensor_158d00022b393c.attributes.battery_level >= 60 %}
                           mdi:battery-60
                        {% elif states.binary_sensor.door_window_sensor_158d00022b393c.attributes.battery_level >= 50 %}
                           mdi:battery-50
                        {% elif states.binary_sensor.door_window_sensor_158d00022b393c.attributes.battery_level >= 40 %}
                           mdi:battery-40
                        {% elif states.binary_sensor.door_window_sensor_158d00022b393c.attributes.battery_level >= 30 %}
                           mdi:battery-30
                        {% elif states.binary_sensor.door_window_sensor_158d00022b393c.attributes.battery_level >= 20 %}
                           mdi:battery-20
                        {% elif states.binary_sensor.door_window_sensor_158d00022b393c.attributes.battery_level >= 10 %}
                           mdi:battery-10
                        {% else %}
                           battery-outline
                        {% endif %}'
#
# AAC. XIAOMI AQARA GATEWAY
xiaomi_aqara:
  gateways:
    - mac: 78:11:DC:B7:88:FA
      key: AD58F3C5D30D405C

# AAC. ALARM MANUAL CONTROL PANEL
#
# Status:  Disarmed => Armed (Home/Night/Away) => Triggered => Disarmed
#
alarm_control_panel:
  - platform: manual
    name: HA
    code: !secret alarm_control_code
    # Pending: The time in seconds of the pending time before effecting a state change. Default is 60 seconds.
    # Delay: The time in seconds of the pending time before triggering the alarm. Default is 0 seconds.
    # Trigger: The time in seconds of the trigger time in which the alarm is firing. Default is 120 seconds
    armed_home:
      pending_time: 0
      delay_time: 0
    armed_away:
      pending_time: 30
      delay_time: 15
    disarmed:
      trigger_time: 0


# AAC. PROSEGUR
#alarm_control_panel:
#  - platform: totalconnect
#    username: agustin.alvarezconesa@gmail.com
#    password: Casuario2018

# AAC. TV Sony
# media_player:
#   - platform: braviatv
#     host: 192.168.0.14
#     name: TV Sony Salón
#   - platform: braviatv
#     host: 192.168.0.15
#     name: TV Sony Estudio
