homeassistant:
  # Name of the location where Home Assistant is running
  name: Arrayán8
  # Location required to calculate the time the sun rises and sets
  latitude: 37.389154
  longitude: -6.093752
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 172
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Madrid
  # Customization file
  customize: !include customize.yaml


# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  api_password: !secret http_password
  ssl_certificate: /etc/letsencrypt/live/alvarea.duckdns.org/fullchain.pem
  ssl_key: /etc/letsencrypt/live/alvarea.duckdns.org/privkey.pem
  base_url: alvarea.duckdns.org

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# AAC. Sensores de Tiempo, sol, Luna,
sensor:
  - platform: yr
    name: Hoy
    monitored_conditions:
      - temperature
      - symbol
  - platform: yr
    name: Mañana
    forecast: 24
    monitored_conditions:
      - temperature
      - symbol
  - platform: time_date
    display_options:
      - 'date'
      - 'time'
      - 'time_utc'
  - platform: uptime
    unit_of_measurement: hours
  - platform: moon
  - platform: cert_expiry
    host: alvarea.duckdns.org
    port: 443

# Text to speech
#tts:
#  - platform: google

# Cloud
#cloud:

# AAC. Philips Hue Bridge
hue:
  bridges:
    - host: 192.168.0.17

# AAC. Dispositivos Apple IOS
ios:

# AAC. GENERIC IP CAMERA
camera:
  - platform: generic
    still_image_url: http://192.168.0.11/snapshot/image0.jpg
    name: IPcam11 Cocina
    username: admin
    password: !secret IPcam11
  - platform: generic
    still_image_url: http://192.168.0.12:8080/snapshot.cgi
    name: IPcam12 Salon
    username: admin
    password: !secret IPcam12

# AAC. MQTT - BROKER: CLOUDMQTT
mqtt:
  broker: m23.cloudmqtt.com
  port: 11024
  client_id: hass_alvarea
  keepalive: 60
  username: HASS
  password: !secret cloudmqtt

# AAC. NMAP, OWNTRACKS
device_tracker:
  - platform: nmap_tracker
    hosts:
      - 192.168.0.10
      - 192.168.0.50-99
    home_interval: 10
    exclude:
     - 192.168.0.23
  - platform: owntracks
    mqtt_topic: "owntracks/#"

input_boolean:
  mfchome:
    name: MFC Home
    initial: off
    icon: mdi:cellphone-iphone
  aachome:
    name: AAC Home
    initial: off
    icon: mdi:cellphone-iphone
  pafhome:
    name: PAF Home
    initial: off
    icon: mdi:cellphone-iphone
  aafhome:
    name: AAF Home
    initial: off
    icon: mdi:cellphone-iphone
