homeassistant:
  # Name of the location where Home Assistant is running
  name: Arrayán8
  # Location required to calculate the time the sun rises and sets
  latitude: 37.389154
  longitude: -6.093752
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 172
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Madrid
  # Customization file
  customize: !include customize.yaml


# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123
  ssl_certificate: /etc/letsencrypt/live/alvarea.duckdns.org/fullchain.pem
  ssl_key: /etc/letsencrypt/live/alvarea.duckdns.org/privkey.pem
  base_url: alvarea.duckdns.org

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# AAC. Sensores de Tiempo, sol, Luna,
sensor:
  - platform: yr
    name: Tiempo
    monitored_conditions:
      - temperature
      - symbol
  - platform: yr
    name: Mañana
    forecast: 24
    monitored_conditions:
      - temperature
      - symbol

# Text to speech
#tts:
#  - platform: google

# Cloud
#cloud:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

# AAC. Philips Hue Bridge
hue:
  bridges:
    - host: 192.168.0.17

# AAC. Dispositivos Apple IOS
ios:

# AAC. TV Sony
# media_player:
#   - platform: braviatv
#     host: 192.168.0.14
#     name: TV Sony Salón
#   - platform: braviatv
#     host: 192.168.0.15
#     name: TV Sony Estudio

# AAC. GENERIC IP CAMERA
camera:
  - platform: generic
    still_image_url: http://192.168.0.11/snapshot/image0.jpg
    name: IPcam11 Entrada
    username: admin
    password: !secret IPcam11
  - platform: generic
    still_image_url: http://192.168.0.12:8080/snapshot.cgi
    name: IPcam12 Estudio
    username: admin
    password: !secret IPcam12

# AAC. WEB SSH TERMINAL
panel_iframe:
  terminal:
    title: 'Terminal'
    icon: mdi:console
    url: 'http://192.168.0.23:4200'
