#
# SONOFF BASIC #1 => SIRENA ALARMA PASILLO
#
esphomeyaml:
  name: sonoff_bas_sw1
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: dout

wifi:
  ssid: 'WLAN.alvarea.net'
  password: '3286202581200'
  manual_ip:
    static_ip: 192.168.0.30
    gateway: 192.168.0.1
    subnet: 255.255.255.0

mqtt:
  broker: '192.168.0.23'
  username: 'switch_sonoff'
  password: '7xnQj7RUc05dHqywDM'

# Enable logging
logger:

ota:

switch:
  - platform: gpio
    name: "sonoff basic sw1"
    pin: GPIO12

output:
  - platform: esp8266_pwm
    id: sonoff_bas_sw1_green_led
    pin:
      number: GPIO13
      inverted: True
