esphomeyaml:
  name: sonoff_pow_sw1
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: dout

wifi:
  ssid: 'WLAN.alvarea.net'
  password: '3286202581200'
  manual_ip:
    static_ip: 192.168.0.38
    gateway: 192.168.0.1
    subnet: 255.255.255.0

mqtt:
  broker: '192.168.0.23'
  username: 'switch_sonoff'
  password: '7xnQj7RUc05dHqywDM'

# Enable logging
#logger:

ota:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Sonoff POW SW1 Boton"
  - platform: status
    name: "Sonoff POW SW1 Status"


switch:
  - platform: gpio
    name: "Sonoff POW SW1"
    pin: GPIO12

output:
  # Register the green LED as a dimmable output ....
  - platform: esp8266_pwm
    id: pow_sw1_green_led
    pin:
      number: GPIO13
      inverted: True

light:
  # ... and then make a light out of it.
  - platform: monochromatic
    name: "Sonoff POW SW1 LED"
    output: pow_sw1_green_led

logger:
  baud_rate: 0

uart:
  rx_pin: RX
  baud_rate: 4800

sensor:
  - platform: cse7766
    current:
      name: "Sonoff Pow SW1 Current"
    voltage:
      name: "Sonoff Pow SW1 Voltage"
    power:
      name: "Sonoff Pow SW1 Power"
