#
# SONOFF BASIC SW4
#
esphomeyaml:
  name: sonoff_bas_sw4
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: dout

wifi:
  ssid: 'WLAN.alvarea.net'
  password: '3286202581200'
  manual_ip:
    static_ip: 192.168.0.34
    gateway: 192.168.0.1
    subnet: 255.255.255.0
mqtt:
  broker: '192.168.0.23'
  username: 'switch_sonoff'
  password: '7xnQj7RUc05dHqywDM'

# Enable logging
logger:

ota:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Sonoff Basic SW4 Boton"
  - platform: status
    name: "Sonoff Basic SW4 Status"

switch:
  - platform: gpio
    name: "Sonoff Basic SW4"
    pin: GPIO12

output:
  - platform: esp8266_pwm
    id: basic_sw4_green_led
    pin:
      number: GPIO13
      inverted: True

light:
  - platform: monochromatic
    name: "Sonoff Basic SW4 LED"
    output: basic_sw4_green_led