esphomeyaml:
  name: sonoff_s20_sw1
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: dout

wifi:
  ssid: 'WLAN.alvarea.net'
  password: '3286202581200'
  manual_ip:
    static_ip: 192.168.0.33
    gateway: 192.168.0.1
    subnet: 255.255.255.0

mqtt:
  broker: '192.168.0.23'
  username: 'switch_sonoff'
  password: '7xnQj7RUc05dHqywDM'

# Enable logging
logger:

ota:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Sonoff S20 SW1 Botón"
  - platform: status
    name: "Sonoff S20 SW1 Status"


switch:
  - platform: gpio
    name: "Sonoff S20 SW1"
    pin: GPIO12

output:
  # Register the green LED as a dimmable output ....
  - platform: esp8266_pwm
    id: s20_sw1_green_led
    pin:
      number: GPIO13
      inverted: True

light:
  # ... and then make a light out of it.
  - platform: monochromatic
    name: "Sonoff S20 SW1 LED"
    output: s20_sw1_green_led